name: ustudy
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  sqflite: ^2.4.2
  equatable: ^2.0.7
  path_provider: ^2.1.5
  path: ^1.9.1
  encrypt: ^5.0.3
  http: ^1.4.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_platform_interface: ^2.13.1
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:

  uses-material-design: true
  assets:
    - assets/data/unis.json
    - assets/logo.png
    - assets/data/preguntas_ia.json
    - assets/data/announcements.json